"""empty message

Revision ID: 1437837be2ec
Revises: None
Create Date: 2016-02-13 11:49:57.299887

"""

# revision identifiers, used by Alembic.
revision = '1437837be2ec'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formulario1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('vehiculo1', sa.String(length=20), nullable=True),
    sa.Column('vehiculo2', sa.String(length=20), nullable=True),
    sa.Column('causa', sa.String(length=20), nullable=True),
    sa.Column('heridos', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('fullname', sa.String(length=80), nullable=True),
    sa.Column('is_boss', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('formulario1')
    ### end Alembic commands ###
