"""empty message

Revision ID: 14f3241c059f
Revises: a18792379b53
Create Date: 2016-02-27 19:17:31.175442

"""

# revision identifiers, used by Alembic.
revision = '14f3241c059f'
down_revision = 'a18792379b53'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formulario1', sa.Column('altura', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formulario1', 'altura')
    ### end Alembic commands ###
