"""empty message

Revision ID: 26265293bf6c
Revises: 1437837be2ec
Create Date: 2016-02-14 11:52:58.871509

"""

# revision identifiers, used by Alembic.
revision = '26265293bf6c'
down_revision = '1437837be2ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formulario1', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('formulario1', sa.Column('long', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formulario1', 'long')
    op.drop_column('formulario1', 'lat')
    ### end Alembic commands ###
