"""empty message

Revision ID: 291fec96640e
Revises: c9ae029c945c
Create Date: 2016-03-20 17:05:12.267346

"""

# revision identifiers, used by Alembic.
revision = '291fec96640e'
down_revision = 'c9ae029c945c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formulario1', sa.Column('vehiculo3', sa.String(length=20), nullable=True))
    op.add_column('formulario1', sa.Column('vehiculo4', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formulario1', 'vehiculo4')
    op.drop_column('formulario1', 'vehiculo3')
    ### end Alembic commands ###
