"""empty message

Revision ID: 7cc646facc5e
Revises: 291fec96640e
Create Date: 2016-03-20 19:34:54.188130

"""

# revision identifiers, used by Alembic.
revision = '7cc646facc5e'
down_revision = '291fec96640e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formulario1', sa.Column('hora_dato', sa.Time(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formulario1', 'hora_dato')
    ### end Alembic commands ###
