"""empty message

Revision ID: a18792379b53
Revises: 26265293bf6c
Create Date: 2016-02-27 18:44:12.697923

"""

# revision identifiers, used by Alembic.
revision = 'a18792379b53'
down_revision = '26265293bf6c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formulario1', sa.Column('calle1', sa.String(length=150), nullable=True))
    op.add_column('formulario1', sa.Column('calle2', sa.String(length=150), nullable=True))
    op.add_column('formulario1', sa.Column('obitos', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formulario1', 'obitos')
    op.drop_column('formulario1', 'calle2')
    op.drop_column('formulario1', 'calle1')
    ### end Alembic commands ###
