"""empty message

Revision ID: b13bb9173d7d
Revises: 14f3241c059f
Create Date: 2016-02-27 21:04:54.575311

"""

# revision identifiers, used by Alembic.
revision = 'b13bb9173d7d'
down_revision = '14f3241c059f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formulario1', sa.Column('precision', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formulario1', 'precision')
    ### end Alembic commands ###
