"""empty message

Revision ID: c9ae029c945c
Revises: b13bb9173d7d
Create Date: 2016-02-28 09:52:05.424256

"""

# revision identifiers, used by Alembic.
revision = 'c9ae029c945c'
down_revision = 'b13bb9173d7d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=True))
    op.drop_column('users', 'is_boss')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_boss', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'level')
    ### end Alembic commands ###
